name = "snugglepile"
author = "Gale"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2adb63cc7651e3c49a1ea5296c10e1db2e7df5555c6aae6d606d9c851690ddf5"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
