name = "snugglepile"
author = "Gale"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa9c2fa292bd6435ddd7386a83def366a2cca261813e306567761095d5e6e203"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
