name = "snugglepile"
author = "Gale"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f9de1093f6b7f9309d8a083f05eb206ad3339cb6901c3be385ef23a536f472e"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
