name = "snugglepile"
author = "Gale"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f52d10fb7f21b9cb067f3f09f9fed8afc84be5190c6b18d516ca044334c893a"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
